# core/holidays_flags.py

COUNTRY_FLAGS = {
    "world": "🌍",
    "russia": "🇷🇺",
    "ukraine": "🇺🇦",
    "georgia": "🇬🇪",
    "armenia": "🇦🇲",
    "kazakhstan": "🇰🇿",
    "poland": "🇵🇱",
    "turkey": "🇹🇷",
    "canada": "🇨🇦",
    "usa": "🇺🇸",
    "spain": "🇪🇸",
    "italy": "🇮🇹",
    "france": "🇫🇷",
    "portugal": "🇵🇹",
    "uae": "🇦🇪",
    "israel": "🇮🇱",
    "eu": "🇪🇺",
    "china": "🇨🇳",
    "india": "🇮🇳",
    "central_african_republic": "🇨🇫",
    "new_zealand": "🇳🇿",
    "chad": "🇹🇩",
    "romania": "🇷🇴",
    "philippines": "🇵🇭",
    "uk": "🇬🇧",
    "laos": "🇱🇦",
    "tonga": "🇹🇴",
    "nepal": "🇳🇵",
    "sri_lanka": "🇱🇰",
    "orthodox": "✝️",
    "catholic": "✝️",
    "muslim": "☪️",
    "jewish": "✡️",
}
