# core/holidays_flags.py

COUNTRY_FLAGS = {
    "world": "🌍",
    "russia": "🇷🇺",
    "ukraine": "🇺🇦",
    "georgia": "🇬🇪",
    "armenia": "🇦🇲",
    "kazakhstan": "🇰🇿",
    "poland": "🇵🇱",
    "turkey": "🇹🇷",
    "canada": "🇨🇦",
    "usa": "🇺🇸",
    "spain": "🇪🇸",
    "italy": "🇮🇹",
    "france": "🇫🇷",
    "portugal": "🇵🇹",
    "uae": "🇦🇪",
    "israel": "🇮🇱",
    "eu": "🇪🇺",
    "china": "🇨🇳",
    "india": "🇮🇳",
    "central_african_republic": "🇨🇫",
    "new_zealand": "🇳🇿",
    "chad": "🇹🇩",
    "romania": "🇷🇴",
    "philippines": "🇵🇭",
    "uk": "🇬🇧",
    "laos": "🇱🇦",
    "tonga": "🇹🇴",
    "nepal": "🇳🇵",
    "sri_lanka": "🇱🇰",


    "orthodox": "✝️",
    "catholic": "✝️",
    "muslim": "☪️",
    "jewish": "✡️",
}

CATEGORY_EMOJIS = {
    "Health": "🩺",
    "Cultural": "🎎",
    "Federal": "🏛️",
    "Special Interest": "⭐",
    "Cause": "🎗️",
    "Food & Beverage": "🍽️",
    "Animal": "🐾",
    "Appreciation": "🙏",
    "Arts & Entertainment": "🎭",
    "Relationship": "❤️",
    "Fun": "🎉",
    "Religion": "⛪",
    "Religious": "⛪",
    "Activity": "⚽",
    "Activities": "⚽",
    "Environment": "🌱",
    "History": "📜",
    "Historical": "📜",
    "Technology": "💻",
    "Education": "📚",
    "Educational": "📚",
    "Safety": "🚨",
    "Fashion": "👗",
    "Lifestyle": "🏡",
}
